[tool.black]
line-length = 79
include = '\.py$'
exclude = '''
/(
    \.git
  | \.venv
  | \.env
  | __pycache__
  | venv
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_after_imports = 2
